name: covid19hr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0 
  flutter_sparkline: ^0.1.0
  flinq: ^1.1.1
  shimmer_animation: ^1.0.0
  flutter_hooks: ^0.16.0
  provider: ^5.0.0-nullsafety.5
  flutter_launcher_icons: ^0.9.0 
  http: ^0.13.0
  fluentui_system_icons: ^1.1.101
  adaptive_theme: ^2.0.0-nullsafety.1
  url_launcher: ^6.0.2 
  expandable_slider: ^1.0.3
  shared_preferences: ^2.0.3
  date_picker_timeline: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/complete-icon.png"
  adaptive_icon_background: "assets/icons/back_plate.png"
  adaptive_icon_foreground: "assets/icons/front_plate.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/inter/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/inter/Inter-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/inter/Inter-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/inter/Inter-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/inter/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/inter/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/inter/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/inter/Inter-BlackItalic.otf
          weight: 900
          style: italic
    - family: DMSans
      fonts:
        - asset: assets/fonts/dmsans/DMSans-Regular.ttf
        - asset: assets/fonts/dmsans/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/dmsans/DMSans-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/dmsans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dmsans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

